version: "3.8"
services:
  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    platform: linux/amd64
    environment:
      SA_PASSWORD: "password123@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_CONFIG_CONNECTIVITY: "LOCAL"
    ports:
      - "1444:1433"

# docker compose -f mssql.yml up -d

# 81%